[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 4

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[coverage]
report_verbosity = 1